# Generated by Django 4.0.4 on 2022-05-22 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_wallet_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
